services:
  rknn-infer:
    build: .
    container_name: orangepi_rknn_runner
    volumes:
      - .:/app
    devices:
      - /dev/rknpu0
      - /dev/dri
      - /dev/rga
    privileged: true
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
