version: '3.8'

services:
  rknn_runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orangepi_rknn_runner
    volumes:
      - .:/app
      - /dev:/dev
    privileged: true
    environment:
      - PYTHONPATH=/app
      - LD_LIBRARY_PATH=/usr/lib
      - TEST_IMAGE=images/img001.png
      - NUM_RUNS=100
    devices:
      - /dev/rknpu0
      - /dev/dri
      - /dev/rga
    command: >
      bash -c "python infer_test.py"
