version: '3.8'

services:
  rknn_runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onnx_to_rknn
    volumes:
      - .:/app
      - /dev:/dev
    working_dir: /app
    privileged: true
    environment:
      - PYTHONPATH=/app
      - LD_LIBRARY_PATH=/usr/lib
    devices:
      - /dev/rknpu0
      - /dev/dri
      - /dev/rga
    command: python convert.py
